language: c
sudo: true
install: sudo apt-get install cppcheck
cache: ccache
env:
- TEST='lint'
- TEST='build'
- TEST='integration'
- TEST='compat' BABELD_B_REVISION='master' BABELD_B_REMOTE='https://github.com/jech/babeld'
script: CI=True ./test.sh
